title: "Jacques van Heerden"
email: jvanheerden38@gmail.com
logo: /assets/img/Headshot.png
description: >-
  Portfolio of Jacques van Heerden. Showcasing experience, projects, skills, and contact details.

# Theme setup
remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Minimal Mistakes Skin
minimal_mistakes_skin: "default"

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Experience"
    url: /experience/
  - title: "Projects"
    url: /projects/
  - title: "Skills"
    url: /skills/
  - title: "Contact"
    url: /contact/

# Author (for SEO/social)
author:
  name: "Jacques van Heerden"
  avatar: "/assets/img/Headshot.png"
  bio: "Solutions Engineer | Software Developer | AI/Automation Engineer"
