title: Jacques van Heerden
logo: /assets/img/Headshot.png
show_downloads: true
theme: jekyll-theme-minimal

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      stylesheet: /assets/css/style.scss
