title: Jacques van Heerden
logo: /assets/img/Headshot.png
show_downloads: true
theme: jekyll-theme-minimal

# Tell Jekyll to use your custom style.scss
sass:
  style: compressed

# Optional: If this doesn’t apply automatically, set this:
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      stylesheet: /assets/css/style.scss
